using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LinkDotNet.Enumeration;

[Generator]
public sealed class EnumerationGenerator : IIncrementalGenerator
{
    private const string FullAttributeName = "LinkDotNet.Enumeration.EnumerationAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        using System;

        namespace LinkDotNet.Enumeration;

        /// <summary>Specifies how static member names are derived from the string values.</summary>
        internal enum Casing
        {
            /// <summary>Converts each value to PascalCase (default).</summary>
            PascalCase,
            /// <summary>Uses the raw string value as the member name.</summary>
            Preserve
        }

        /// <summary>
        /// Marks a <c>partial class</c> or <c>partial record</c> as a source-generated enumeration.
        /// The generator emits: Key property, private constructor, static readonly fields,
        /// All, Create, TryCreate, == / != operators, ToString, Match&lt;T&gt; and Match(Action).
        /// </summary>
        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class EnumerationAttribute : Attribute
        {
            public string[] Values { get; }
            public Casing MemberCasing { get; }
            /// <summary>
            /// When <see langword="true"/>, a <see cref="System.Text.Json.Serialization.JsonConverterAttribute"/>
            /// is applied to the enumeration type and a <c>{TypeName}JsonConverter</c> class is generated
            /// that serializes and deserializes the type as its <c>Key</c> string using
            /// <see cref="System.Text.Json.JsonSerializer"/>.
            /// </summary>
            public bool GenerateJsonConverter { get; init; }
            public EnumerationAttribute(params string[] values) => (Values, MemberCasing) = (values, Casing.PascalCase);
            public EnumerationAttribute(Casing casing, params string[] values) => (Values, MemberCasing) = (values, casing);
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("EnumerationAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FullAttributeName,
                predicate: static (node, _) => node is RecordDeclarationSyntax or ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(models, static (spc, model) => Emit(spc, model!));
    }

    private static EnumerationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
        {
            return null;
        }

        var attr = ctx.Attributes.FirstOrDefault();
        if (attr is null || attr.ConstructorArguments.Length == 0)
        {
            return null;
        }

        ImmutableArray<TypedConstant> rawValues;
        var isPreserve = false;

        if (attr.ConstructorArguments[0].Kind == TypedConstantKind.Enum)
        {
            isPreserve = attr.ConstructorArguments[0].Value is 1;
            var valuesArg = attr.ConstructorArguments[1];
            rawValues = valuesArg.Kind == TypedConstantKind.Array ? valuesArg.Values : [valuesArg];
        }
        else
        {
            var arg = attr.ConstructorArguments[0];
            rawValues = arg.Kind == TypedConstantKind.Array ? arg.Values : [arg];
        }

        var values = rawValues
            .Select(static v => v.Value as string)
            .Where(static v => v is not null)
            .Select(static v => v!)
            .ToImmutableArray();

        if (values.IsEmpty)
        {
            return null;
        }

        var entries = values
            .Select(v => new EnumerationEntry(v, isPreserve ? v : ToPascalCase(v)))
            .ToImmutableArray();

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();

        var isRecord = ctx.TargetNode is RecordDeclarationSyntax;
        var accessibility = type.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "public"
        };

        var parentTypes = ImmutableArray.CreateBuilder<ParentType>();
        var parent = type.ContainingType;
        while (parent is not null)
        {
            var kind = parent.IsRecord ? "record" : "class";
            var parentAccessibility = parent.DeclaredAccessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.ProtectedAndInternal => "private protected",
                _ => "public"
            };
            parentTypes.Insert(0, new ParentType(parent.Name, kind, parentAccessibility));
            parent = parent.ContainingType;
        }

        var generateJsonConverter = attr.NamedArguments
            .Any(a => a.Key == "GenerateJsonConverter" && a.Value.Value is true);

        return new EnumerationModel(ns, type.Name, entries, isRecord, accessibility, parentTypes.ToImmutable(), generateJsonConverter);
    }

    /// <summary>
    /// Converts a raw string value to a valid PascalCase C# identifier.
    /// Splits on '_', '-', '.', or ' ', then title-cases each segment.
    /// All-uppercase segments (e.g. "OK", "DANGER") are lowered after the first character.
    /// </summary>
    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        var segments = value.Split('_', '-', '.', ' ');
        var sb = new StringBuilder();

        foreach (var segment in segments)
        {
            if (segment.Length == 0)
            {
                continue;
            }

            sb.Append(char.ToUpperInvariant(segment[0]));

            if (segment.Length > 1)
            {
                // All-uppercase segment (e.g. "OK", "DANGER") → lowercase the tail
                var tail = segment.Length > 1 && segment == segment.ToUpperInvariant()
                    ? segment.Substring(1).ToLowerInvariant()
                    : segment.Substring(1);

                sb.Append(tail);
            }
        }

        return sb.ToString();
    }

    private static void Emit(SourceProductionContext ctx, EnumerationModel model)
    {
        var sb = new StringBuilder(4000);
        var typeName = model.TypeName;
        var allFieldNames = string.Join(", ", model.Entries.Select(static e => e.MemberName));

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        if (model.GenerateJsonConverter)
        {
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Serialization;");
        }

        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        foreach (var parent in model.ParentTypes)
        {
            sb.AppendLine($"{parent.Accessibility} partial {parent.Kind} {parent.Name}");
            sb.AppendLine("{");
        }

        var typeKind = model.IsRecord ? "record" : "class";
        var interfaceImplementations = new List<string> { $"IParsable<{typeName}>", $"ISpanParsable<{typeName}>", "ISpanFormattable" };
        if (!model.IsRecord)
        {
            interfaceImplementations.Add($"IEquatable<{typeName}>");
        }

        var interfaces = string.Join(", ", interfaceImplementations);

        if (model.GenerateJsonConverter)
        {
            sb.AppendLine($"[JsonConverter(typeof({typeName}JsonConverter))]");
        }

        sb.AppendLine("[DebuggerDisplay(\"{Key}\")]");
        sb.AppendLine($"{model.Accessibility} sealed partial {typeKind} {typeName} : {interfaces}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>Gets the string key that identifies this enumeration value.</summary>");
        sb.AppendLine("    public string Key { get; init; } = default!;");
        sb.AppendLine();

        sb.AppendLine($"    private {typeName}(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentException.ThrowIfNullOrWhiteSpace(key);");
        sb.AppendLine("        Key = key;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <summary>Gets the <see cref=\"{typeName}\"/> instance for <c>{entry.Key}</c>.</summary>");
            sb.AppendLine($"    public static readonly {typeName} {entry.MemberName} = new(\"{entry.Key}\");");
        }

        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Gets a frozen set of all valid <see cref=\"{typeName}\"/> instances. Ordering is not guaranteed.</summary>");
        sb.AppendLine($"    public static FrozenSet<{typeName}> All {{ get; }} =");
        sb.AppendLine($"        new {typeName}[] {{ {allFieldNames} }}.ToFrozenSet();");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Creates the <see cref=\"{typeName}\"/> instance matching <paramref name=\"key\"/>.</summary>");
        sb.AppendLine("    /// <param name=\"key\">The key to look up. Must not be null, empty, or whitespace.</param>");
        sb.AppendLine($"    /// <returns>The matching <see cref=\"{typeName}\"/> instance.</returns>");
        sb.AppendLine("    /// <exception cref=\"ArgumentException\">Thrown when <paramref name=\"key\"/> is null, empty, or whitespace.</exception>");
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when <paramref name=\"key\"/> does not match any known value.</exception>");
        sb.AppendLine($"    public static {typeName} Create(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentException.ThrowIfNullOrWhiteSpace(key);");
        sb.AppendLine("        return key switch");
        sb.AppendLine("        {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"            \"{entry.Key}\" => {entry.MemberName},");
        }
        sb.AppendLine($"            _ => throw new InvalidOperationException($\"{{key}} is not a valid value for {typeName}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Tries to create the <see cref=\"{typeName}\"/> instance matching <paramref name=\"key\"/>.</summary>");
        sb.AppendLine("    /// <param name=\"key\">The key to look up.</param>");
        sb.AppendLine($"    /// <param name=\"value\">When this method returns <see langword=\"true\"/>, contains the matching <see cref=\"{typeName}\"/> instance; otherwise <see langword=\"null\"/>.</param>");
        sb.AppendLine("    /// <returns><see langword=\"true\"/> if a matching instance was found; otherwise <see langword=\"false\"/>.</returns>");
        sb.AppendLine($"    public static bool TryCreate(string? key, [NotNullWhen(true)] out {typeName}? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        value = key switch");
        sb.AppendLine("        {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"            \"{entry.Key}\" => {entry.MemberName},");
        }
        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("        return value is not null;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Tries to create the <see cref=\"{typeName}\"/> instance matching <paramref name=\"key\"/> without allocating a string.</summary>");
        sb.AppendLine("    /// <param name=\"key\">The key span to look up.</param>");
        sb.AppendLine($"    /// <param name=\"value\">When this method returns <see langword=\"true\"/>, contains the matching <see cref=\"{typeName}\"/> instance; otherwise <see langword=\"null\"/>.</param>");
        sb.AppendLine("    /// <returns><see langword=\"true\"/> if a matching instance was found; otherwise <see langword=\"false\"/>.</returns>");
        sb.AppendLine($"    public static bool TryCreate(ReadOnlySpan<char> key, [NotNullWhen(true)] out {typeName}? value)");
        sb.AppendLine("    {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"        if (MemoryExtensions.Equals(key, \"{entry.Key}\".AsSpan(), StringComparison.Ordinal))");
            sb.AppendLine($"        {{ value = {entry.MemberName}; return true; }}");
        }
        sb.AppendLine("        value = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public static {typeName} Parse(string s, IFormatProvider? provider) => Create(s);");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public static bool TryParse(string? s, IFormatProvider? provider, [NotNullWhen(true)] out {typeName}? result) => TryCreate(s, out result);");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public static {typeName} Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => Create(s.ToString());");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, [NotNullWhen(true)] out {typeName}? result) => TryCreate(s, out result);");
        sb.AppendLine();

        if (!model.IsRecord)
        {
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine($"    public bool Equals({typeName}? other) => other is not null && Key.Equals(other.Key, StringComparison.Ordinal);");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine($"    public override bool Equals(object? obj) => obj is {typeName} other && Equals(other);");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine("    public override int GetHashCode() => Key.GetHashCode();");
            sb.AppendLine();
        }

        sb.AppendLine($"    /// <summary>Returns <see langword=\"true\"/> when <paramref name=\"a\"/>'s key equals <paramref name=\"b\"/> using ordinal string comparison.</summary>");
        sb.AppendLine($"    public static bool operator ==({typeName}? a, string? b)");
        sb.AppendLine("        => a is not null && b is not null && a.Key.Equals(b, StringComparison.Ordinal);");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Returns <see langword=\"true\"/> when <paramref name=\"a\"/>'s key does not equal <paramref name=\"b\"/>.</summary>");
        sb.AppendLine($"    public static bool operator !=({typeName}? a, string? b) => !(a == b);");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Implicitly converts the <see cref=\"{typeName}\"/> instance to its <see cref=\"Key\"/>.</summary>");
        sb.AppendLine($"    public static implicit operator string({typeName} value) => value.Key;");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Explicitly converts the <see cref=\"string\"/> to a <see cref=\"{typeName}\"/> instance.</summary>");
        sb.AppendLine($"    public static explicit operator {typeName}(string key) => Create(key);");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>Returns the key of this enumeration value.</summary>");
        sb.AppendLine("    /// <returns>The <see cref=\"Key\"/> string.</returns>");
        sb.AppendLine("    public override string ToString() => Key;");
        sb.AppendLine();

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Key.AsSpan().TryCopyTo(destination))");
        sb.AppendLine("        {");
        sb.AppendLine("            charsWritten = Key.Length;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        charsWritten = 0;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string ToString(string? format, IFormatProvider? provider) => Key;");
        sb.AppendLine();

        var valueParams = string.Join(", ", model.Entries.Select(static e => $"T on{e.MemberName}"));
        sb.AppendLine("    /// <summary>Returns the value corresponding to the current enumeration value.</summary>");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <param name=\"on{entry.MemberName}\">Returned when the current value is <see cref=\"{entry.MemberName}\"/>.</param>");
        }
        sb.AppendLine("    /// <typeparam name=\"T\">The return type.</typeparam>");
        sb.AppendLine("    /// <returns>The matched value.</returns>");
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when no case matches.</exception>");
        sb.AppendLine($"    public T Match<T>({valueParams})");
        sb.AppendLine("    {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"        if (Key == {entry.MemberName}.Key) return on{entry.MemberName};");
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Unhandled enumeration value: {Key}\");");
        sb.AppendLine("    }");
        sb.AppendLine();

        var funcParams = string.Join(", ", model.Entries.Select(static e => $"Func<T> on{e.MemberName}"));
        sb.AppendLine("    /// <summary>Invokes the function corresponding to the current value and returns its result.</summary>");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <param name=\"on{entry.MemberName}\">Invoked when the current value is <see cref=\"{entry.MemberName}\"/>.</param>");
        }
        sb.AppendLine("    /// <typeparam name=\"T\">The return type.</typeparam>");
        sb.AppendLine("    /// <returns>The value returned by the matched function.</returns>");
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when no case matches.</exception>");
        sb.AppendLine($"    public T Match<T>({funcParams})");
        sb.AppendLine("    {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"        if (Key == {entry.MemberName}.Key) return on{entry.MemberName}();");
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Unhandled enumeration value: {Key}\");");
        sb.AppendLine("    }");
        sb.AppendLine();

        var actionParams = string.Join(", ", model.Entries.Select(static e => $"Action on{e.MemberName}"));
        sb.AppendLine("    /// <summary>Invokes the action corresponding to the current value.</summary>");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <param name=\"on{entry.MemberName}\">Invoked when the current value is <see cref=\"{entry.MemberName}\"/>.</param>");
        }
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when no case matches.</exception>");
        sb.AppendLine($"    public void Match({actionParams})");
        sb.AppendLine("    {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"        if (Key == {entry.MemberName}.Key) {{ on{entry.MemberName}(); return; }}");
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Unhandled enumeration value: {Key}\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        if (model.GenerateJsonConverter)
        {
            var converterName = $"{typeName}JsonConverter";
            sb.AppendLine();
            sb.AppendLine($"/// <summary>A <see cref=\"JsonConverter{{T}}\"/> for <see cref=\"{typeName}\"/> that reads and writes the <c>Key</c> string.</summary>");
            sb.AppendLine($"{model.Accessibility} sealed class {converterName} : JsonConverter<{typeName}>");
            sb.AppendLine("{");
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine($"    public override {typeName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (reader.TokenType != JsonTokenType.String)");
            sb.AppendLine($"            throw new JsonException($\"Expected a JSON string for {typeName}, got {{reader.TokenType}}.\");");
            sb.AppendLine("        var key = reader.GetString();");
            sb.AppendLine("        if (key is null)");
            sb.AppendLine($"            throw new JsonException(\"Expected a non-null string value for {typeName}.\");");
            sb.AppendLine($"        if (!{typeName}.TryCreate(key, out var result))");
            sb.AppendLine($"            throw new JsonException($\"\\\"{{key}}\\\" is not a valid {typeName} value.\");");
            sb.AppendLine("        return result;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <inheritdoc />");
            sb.AppendLine($"    public override void Write(Utf8JsonWriter writer, {typeName} value, JsonSerializerOptions options)");
            sb.AppendLine("        => writer.WriteStringValue(value.Key);");
            sb.AppendLine("}");
        }

        foreach (var _ in model.ParentTypes)
        {
            sb.AppendLine("}");
        }

        ctx.AddSource($"{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal sealed record EnumerationModel(
    string? Namespace,
    string TypeName,
    ImmutableArray<EnumerationEntry> Entries,
    bool IsRecord,
    string Accessibility,
    ImmutableArray<ParentType> ParentTypes,
    bool GenerateJsonConverter);

internal sealed record ParentType(string Name, string Kind, string Accessibility);

internal readonly record struct EnumerationEntry(string Key, string MemberName);

