using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LinkDotNet.Enumeration;

[Generator]
public sealed class EnumerationGenerator : IIncrementalGenerator
{
    private const string FullAttributeName = "LinkDotNet.Enumeration.EnumerationAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        using System;

        namespace LinkDotNet.Enumeration;

        /// <summary>
        /// Marks a <c>sealed partial record</c> as a source-generated enumeration.
        /// The generator emits: Key property, private constructor, static readonly fields,
        /// All, Create, == / != operators, ToString, Match&lt;T&gt; and Match(Action).
        /// </summary>
        [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class EnumerationAttribute : Attribute
        {
            public string[] Values { get; }
            public EnumerationAttribute(params string[] values) => Values = values;
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("EnumerationAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FullAttributeName,
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(models, static (spc, model) => Emit(spc, model!));
    }

    private static EnumerationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
        {
            return null;
        }

        var attr = ctx.Attributes.FirstOrDefault();
        if (attr is null || attr.ConstructorArguments.Length == 0)
        {
            return null;
        }

        var arg = attr.ConstructorArguments[0];
        var rawValues = arg.Kind == TypedConstantKind.Array ? arg.Values : [arg];

        var values = rawValues
            .Select(static v => v.Value as string)
            .Where(static v => v is not null)
            .Select(static v => v!)
            .ToImmutableArray();

        if (values.IsEmpty)
        {
            return null;
        }

        var entries = values
            .Select(static v => new EnumerationEntry(v, ToPascalCase(v)))
            .ToImmutableArray();

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();

        return new EnumerationModel(ns, type.Name, entries);
    }

    /// <summary>
    /// Converts a raw string value to a valid PascalCase C# identifier.
    /// Splits on '_', '-', '.', or ' ', then title-cases each segment.
    /// All-uppercase segments (e.g. "OK", "DANGER") are lowered after the first character.
    /// </summary>
    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        var segments = value.Split('_', '-', '.', ' ');
        var sb = new StringBuilder();

        foreach (var segment in segments)
        {
            if (segment.Length == 0)
            {
                continue;
            }

            sb.Append(char.ToUpperInvariant(segment[0]));

            if (segment.Length > 1)
            {
                // All-uppercase segment (e.g. "OK", "DANGER") → lowercase the tail
                var tail = segment.Length > 1 && segment == segment.ToUpperInvariant()
                    ? segment.Substring(1).ToLowerInvariant()
                    : segment.Substring(1);

                sb.Append(tail);
            }
        }

        return sb.ToString();
    }

    private static void Emit(SourceProductionContext ctx, EnumerationModel model)
    {
        var sb = new StringBuilder();
        var typeName = model.TypeName;
        var allFieldNames = string.Join(", ", model.Entries.Select(static e => e.MemberName));

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public sealed partial record {typeName}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>Gets the string key that identifies this enumeration value.</summary>");
        sb.AppendLine("    public string Key { get; init; } = default!;");
        sb.AppendLine();

        sb.AppendLine($"    private {typeName}(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentException.ThrowIfNullOrWhiteSpace(key);");
        sb.AppendLine("        Key = key;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <summary>Gets the <see cref=\"{typeName}\"/> instance for <c>{entry.Key}</c>.</summary>");
            sb.AppendLine($"    public static readonly {typeName} {entry.MemberName} = new(\"{entry.Key}\");");
        }

        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Gets a frozen set of all valid <see cref=\"{typeName}\"/> instances. Ordering is not guaranteed.</summary>");
        sb.AppendLine($"    public static FrozenSet<{typeName}> All {{ get; }} =");
        sb.AppendLine($"        new {typeName}[] {{ {allFieldNames} }}.ToFrozenSet();");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Creates the <see cref=\"{typeName}\"/> instance matching <paramref name=\"key\"/>.</summary>");
        sb.AppendLine("    /// <param name=\"key\">The key to look up. Must not be null, empty, or whitespace.</param>");
        sb.AppendLine($"    /// <returns>The matching <see cref=\"{typeName}\"/> instance.</returns>");
        sb.AppendLine("    /// <exception cref=\"ArgumentException\">Thrown when <paramref name=\"key\"/> is null, empty, or whitespace.</exception>");
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when <paramref name=\"key\"/> does not match any known value.</exception>");
        sb.AppendLine($"    public static {typeName} Create(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentException.ThrowIfNullOrWhiteSpace(key);");
        sb.AppendLine("        return key switch");
        sb.AppendLine("        {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"            \"{entry.Key}\" => {entry.MemberName},");
        }
        sb.AppendLine($"            _ => throw new InvalidOperationException($\"{{key}} is not a valid value for {typeName}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Returns <see langword=\"true\"/> when <paramref name=\"a\"/>'s key equals <paramref name=\"b\"/> using ordinal string comparison.</summary>");
        sb.AppendLine($"    public static bool operator ==({typeName}? a, string? b)");
        sb.AppendLine("        => a is not null && b is not null && a.Key.Equals(b, StringComparison.Ordinal);");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Returns <see langword=\"true\"/> when <paramref name=\"a\"/>'s key does not equal <paramref name=\"b\"/>.</summary>");
        sb.AppendLine($"    public static bool operator !=({typeName}? a, string? b) => !(a == b);");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>Returns the key of this enumeration value.</summary>");
        sb.AppendLine("    /// <returns>The <see cref=\"Key\"/> string.</returns>");
        sb.AppendLine("    public override string ToString() => Key;");
        sb.AppendLine();

        var funcParams = string.Join(", ", model.Entries.Select(static e => $"Func<T> on{e.MemberName}"));
        sb.AppendLine("    /// <summary>Invokes the function corresponding to the current value and returns its result.</summary>");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <param name=\"on{entry.MemberName}\">Invoked when the current value is <see cref=\"{entry.MemberName}\"/>.</param>");
        }
        sb.AppendLine("    /// <typeparam name=\"T\">The return type.</typeparam>");
        sb.AppendLine("    /// <returns>The value returned by the matched function.</returns>");
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when no case matches.</exception>");
        sb.AppendLine($"    public T Match<T>({funcParams})");
        sb.AppendLine("    {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"        if (Key == {entry.MemberName}.Key) return on{entry.MemberName}();");
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Unhandled enumeration value: {Key}\");");
        sb.AppendLine("    }");
        sb.AppendLine();

        var actionParams = string.Join(", ", model.Entries.Select(static e => $"Action on{e.MemberName}"));
        sb.AppendLine("    /// <summary>Invokes the action corresponding to the current value.</summary>");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"    /// <param name=\"on{entry.MemberName}\">Invoked when the current value is <see cref=\"{entry.MemberName}\"/>.</param>");
        }
        sb.AppendLine("    /// <exception cref=\"InvalidOperationException\">Thrown when no case matches.</exception>");
        sb.AppendLine($"    public void Match({actionParams})");
        sb.AppendLine("    {");
        foreach (var entry in model.Entries)
        {
            sb.AppendLine($"        if (Key == {entry.MemberName}.Key) {{ on{entry.MemberName}(); return; }}");
        }

        sb.AppendLine("        throw new InvalidOperationException($\"Unhandled enumeration value: {Key}\");");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        ctx.AddSource($"{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal sealed class EnumerationModel
{
    public EnumerationModel(string? ns, string typeName, ImmutableArray<EnumerationEntry> entries)
    {
        Namespace = ns;
        TypeName = typeName;
        Entries = entries;
    }

    public string? Namespace { get; }
    public string TypeName { get; }
    public ImmutableArray<EnumerationEntry> Entries { get; }
}

internal readonly record struct EnumerationEntry(string Key, string MemberName);

